services:
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-saas_starter}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-saas_starter}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: elysia_app
    restart: always
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      postgres_db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3000}
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres_db:5432/${POSTGRES_DB:-saas_starter}
      REDIS_URL: redis://redis:6379

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrate
    restart: "no"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres_db:5432/${POSTGRES_DB:-saas_starter}
      SEED_USER_NAME: ${SEED_USER_NAME:-Administrador}
      SEED_USER_EMAIL: ${SEED_USER_EMAIL:-admin@pncp.local}
      SEED_USER_PASSWORD: ${SEED_USER_PASSWORD:-admin123}
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
